### ISSUE TITLE
TOP exercise 기반 프레임워크 및 샘플 준비

### ISSUE THREAD

**Issue by jhgoh** [cms-kr/CMSDAS#2]
강의자들간 빠르고 정확한 의사소통 및 대부분 학생들이 읽을 필요 없으므로 한국어로 작성.

가장 최근 release의 캣툴과 샘플을 활용
- 76X브랜치
- v7-6-2샘플, 추가 프로덕션 가능
- CMSSW_7_6_3_patch2
  - [ ] NTU cluster에 CVMFS캐쉬 업데이트 해서 76X release 사용 가능하게 할것

샘플 처리 시간과 파일 복사 시간, 디스크 공간 문제를 줄이기 위해 step4까지 preselection까지
- Step 4 = dilepton & Z-veto & nJet2 & MET
- Histogram based filter 모듈을 이용해 컨트롤 플랏 및 sumweight정보를 제공
## tasks
- [ ] Check cut flow in event selector module
- [ ] Check event content after sample reduction - are they enough for the physics analysis?
- [ ] Background samples
- Mass samples
  - [ ] catTuple production
  - [ ] sample reduction
- [ ] Copy samples to NT

**Comment by jhgoh** [comment]
Event contents는 여기에 정의됨
https://github.com/cms-kr/CMSDAS/blob/master/TopQuarkAnalysis/python/eventContents_cff.py

학생들이 analyzer module을 작성하게 되면 eventTTLL 모듈의 output을 활용하면 됨.

```
Type                           Module                 Label             Process   
----------------------------------------------------------------------------------
edm::TriggerResults            "TriggerResults"       ""                "SIM"     
edm::TriggerResults            "TriggerResults"       ""                "HLT"     
edm::TriggerResults            "TriggerResults"       ""                "RECO"    
edm::TriggerResults            "TriggerResults"       ""                "PAT"     
vector<reco::GenJet>           "slimmedGenJets"       ""                "PAT"     
vector<reco::GenParticle>      "prunedGenParticles"   ""                "PAT"     
edm::TriggerResults            "TriggerResults"       ""                "CAT"     
float                          "pileupWeight"         ""                "CAT"     
float                          "pileupWeight"         "dn"              "CAT"     
float                          "genWeight"            "genWeight"       "CAT"     
float                          "genWeight"            "lheWeight"       "CAT"     
float                          "pileupWeight"         "up"              "CAT"     
int                            "partonTop"            "channel"         "CAT"     
int                            "catVertex"            "nGoodPV"         "CAT"     
int                            "pileupWeight"         "nTrueInteraction"   "CAT"     
vector<float>                  "genWeight"            "pdfWeights"      "CAT"     
vector<float>                  "genWeight"            "scaleWeights"    "CAT"     
vector<int>                    "partonTop"            "modes"           "CAT"     
vector<reco::GenJet>           "partonTop"            "qcdJets"         "CAT"     
vector<reco::GenParticle>      "partonTop"            ""                "CAT"     
edm::TriggerResults            "TriggerResults"       ""                "CATeX"   
float                          "eventsTTLL"           "met"             "CATeX"   
float                          "eventsTTLL"           "metphi"          "CATeX"   
float                          "eventsTTLL"           "weight"          "CATeX"   
int                            "filterRECO"           ""                "CATeX"   
int                            "filterTrigELEL"       ""                "CATeX"   
int                            "filterTrigMUEL"       ""                "CATeX"   
int                            "filterTrigMUMU"       ""                "CATeX"   
int                            "eventsTTLL"           "channel"         "CATeX"   
vector<cat::Jet>               "eventsTTLL"           "jets"            "CATeX"   
vector<cat::Lepton>            "eventsTTLL"           "leptons"         "CATeX"   
```

**Comment by jhgoh** [comment]
Event selection module은 TTLLEventSelector 모듈을 이용. 여기에서 step5 까지의 기본적인 control plot들을 모두 만들고 event filter까지 해 준다.
https://github.com/vallot/CATTools/blob/cat76x/CatAnalyzer/plugins/TTLLEventSelector.cc

cut step은 top reference selection을 그대로 가져온다.
https://twiki.cern.ch/twiki/bin/view/CMS/TopEventSelection

@geonmo , event selection 들 한번 더 확인 해 주세요.
확인됐으면 맨 위 글의 체크박스 클릭

**Comment by jhgoh** [comment]
현재까지 76X  catTools로 준비는 여러울 듯 하므로 기존 LPC버젼으로 exercise진행해야 할 것으로 보임.
